Redesign EQUAL_WAVE_WRAPPER for identical wave references
byte-physics/igor-unit-testing-framework pull request #276
Opened 2022-10-18 08:58 UTC by Garados007

Enables CHECK_EQUAL_WAVES, WARN_EQUAL_WAVES and REQUIRE_EQUAL_WAVES to accept two identical wave references.

Before this change it will always return an error.

This bug was nowhere mentioned in documentation or test examples.

Close #49

2022-10-18 11:00 UTC, t-b commented
If you search for EQUAL_WAVE_WRAPPER in the repo you will find some matches in VTTE.ipf. This is the "Very tiny test Environment", basically a test framework for our test framework.

Adding something like

```
	UTF_Wrapper#EQUAL_WAVE_WRAPPER(numData1, numData1, !OUTPUT_MESSAGE)
```

should do the trick  which means it only passes with your fix now (untested).

2022-10-18 11:54 UTC, Garados007 commented
Uff. wrong branch.

2022-10-18 12:04 UTC, Garados007 commented
Everything fixed up again. I have to be more careful next time.

2022-10-18 12:06 UTC, t-b commented
> I have to be more careful next time.

Yes, but you also don't break anything permanently. The git reflog has all previous versions.

2022-10-18 14:06 UTC, Garados007 commented
I added the [testcase](https://github.com/byte-physics/igor-unit-testing-framework/pull/276#issuecomment-1282205602).

2022-10-18 14:07 UTC, MichaelHuth requested changes
In the commit message it should not read that this was a bug, but it is merely a conceptional change as the previous concept that two waves that actually reference the same wave are evaluated unequal was unintuitive.

Please add also a brief line in the docu through the description lines in front of the function for the assertion that states this behavior.

2022-10-18 21:00 UTC, t-b commented
I concur with what Michael said.

2022-10-19 16:34 UTC, t-b approved these changes
LGTM.

2022-10-20 16:57 UTC, merged