unit-testing-assertion-wrappers.ipf: Prefer GetNiceStringForNumber
byte-physics/igor-unit-testing-framework pull request #293
Opened 2022-10-29 13:35 UTC by t-b

In that way we have always all digits printed out instead of only the first six as %g does.

Close #292.

2022-10-30 10:43 UTC, Garados007 approved these changes
LGTM

2022-11-01 13:24 UTC, MichaelHuth requested changes
Code looks good.

I think it is not required to commit IMTest.pxp as there are no effective changes made?

2022-11-01 13:26 UTC, t-b commented
> I think it is not required to commit IMTest.pxp as there are no effective changes made?

Thanks again! Fixed.

2022-11-01 13:40 UTC, MichaelHuth approved these changes
Ok

2022-11-01 13:40 UTC, merged