Abort test run if RTE ocurred in UTF
byte-physics/igor-unit-testing-framework pull request #295
Opened 2022-10-30 13:06 UTC by Garados007

Abort the test run if some unhandled RTE still exists before CallTestCase(). These errors are most likely a bug in UTF and leave the UTF in an inconsistent state. It is more safe to stop the run at that moment instead of continuing it.

Before this change any RTE that could happen before the run of the test case are just ignored and thrown away.

Close #264.

2022-11-02 16:02 UTC, t-b commented
Review:

Your code works, and its even a creative use of AbortONRTE. But I'd suggest a slightly different implementation.
- Query the RTE state with GetRTError() passing `0` only queries it, whereas `1` also clears it
- Returning immediately is not the right thing I think. Although you are right that we are in a problematic state as something went wrong, we still can try to finish as usual in the error case. CallTestCase does the triumvirate of

```
					sprintf msg, "Fatal: Reentry function %s does not meet required format for Complex argument.", func
					UTF_PrintStatusMessage(msg)
					incrError()
					abortNow()
```

which actually should be wrapped in a function. That works I think better. Or maybe like AfterTestCase does it.

- Don't introduce a message type like "CRTITAL" adhoc. This would need a planned and documented appraoch.

2022-11-03 10:21 UTC, Garados007 commented
If I introduce the following error in UTF:
```diff
diff --git a/procedures/unit-testing-basics.ipf b/procedures/unit-testing-basics.ipf
index 1579bd5..5781866 100644
--- a/procedures/unit-testing-basics.ipf
+++ b/procedures/unit-testing-basics.ipf
@@ -3688,6 +3688,9 @@ Function RunTest(procWinList, [name, testCase, enableJU, enableTAP, enableRegExp
 
 			if(!skip)
 
+				Wave test = $""
+				variable testvar = test[0]
+
 				if(GetRTError(0))
 					message = GetRTErrMessage()
 					err = GetRTError(1)
```

I get the following output:
```
  Start of test "Unnamed"
  Entering test suite "Proc0"
  Entering test case "mymodule#Test4"
  Fatal: Internal runtime error in UTF 330:"a wave read;Attempt to operate on a null (missing) wave" before executing test case "mymodule#Test4".
  Leaving test case "mymodule#Test4"
  Failed with 1 errors
  Leaving test suite "Proc0"
  Test finished with 1 errors
  End of test "Unnamed"
```

2022-11-03 11:53 UTC, t-b commented
Review:
015108aa (Simplify the report of internal errors, 2022-11-03)

This looks much nicer! Would it make sense to convert even more ad-hoc error reporting to the new infrastructure?

```
git grep -P --show-function "\b(incrError|Abort)\b"
```

has some more matches.

Code:
```
+       sprintf msg, "Fatal: %s", message
```

This might break on <= IP7 due to sprintf limitations. `+` is better here as you don't know how long message is.

```
+       if(ParamIsDefault(abort) || abort)
```

Our default approach is to handle optional arguments after declaring variables and then later on use the result. You are also not forcing `abort` to a boolean value (0/1).

So something like `abort = ParamIsDefault(abort) ? 0 : !!abort` or with `if` in multiple lines.

49722281 (Abort test run if RTE ocurred in UTF, 2022-10-30)

That looks good!

2022-11-03 13:08 UTC, Garados007 commented
I have changed the reporting functions. Now there are two function: `ReportError` and `ReportErrorAndAbort`. Also the whole code base is changed to use one of the two functions instead calling `incrError` and aborting themself. There is a single point left which is not changed. And that is `ReportResults` in `unit-testing-basics.ipf`.

As the result the function `abortNow()` is no longer really used. Only one example and `ReportResults` is calling it. But I cannot remove it because it is marked as public.

2022-11-03 15:29 UTC, t-b commented
>As the result the function abortNow() is no longer really used. Only one example and ReportResults is calling it. But I cannot remove it because it is marked as public.
 
Although it is public we don't advertise it as being part of our official API. Our public API is everything which is covered by doyxgen. We use the HIDDEN_SYMBOL `@cond/@endcond` approach to hide everything else from doxygen.

2022-11-03 19:09 UTC, t-b commented
Review:

- [ ] Nit pick: Please use spaces for alignment, we only indent with tabs. Yes the existing does it also wrong...
- [ ] ReportErrorAndAbort: Don't use `Abort message` as that pop ups a dialog which breaks non-interactive use. Just `Abort`  is fine.
- [ ] The use of `incrError()` in UTFBackgroundMonitor can also be replaced with ReportError I guess.
- [ ] There are still some `Abort`s in place, see `git grep --show-function -C3 "^[[:space:]]*Abort\b" procedures/`. I think all except the last one can use ReportErrorAndAbort. The last should actually just use `return 0` IMHO.
- [ ] Now we are getting close to feature creep, but there are a couple of places where `UTF_PrintStatusMessage` should be replaced with ReportError/ReportErrorAndAbort. Some can be found with ` git grep -A1 "sprintf msg, \"Error"`
- [ ] Please rebase against main to also nicify the changes from b608fc6f (Tracing: Handle TUFXOP erros in Z_ function, 2022-11-02).
- [ ] Can you add some developer documentation to EvaluateResults so what we know when to use this one and when ReportError/ReportErrorAndAbort.

Thanks!

2022-11-03 21:02 UTC, t-b requested changes
See comment.

2022-11-07 13:17 UTC, Garados007 commented
> Please rebase against main to also nicify the changes from https://github.com/byte-physics/igor-unit-testing-framework/commit/b608fc6f743b0f8bd4046a14174110dfd8d67afa (Tracing: Handle TUFXOP erros in Z_ function, 2022-11-02).
Thanks for pointing out this problem.

2022-11-07 13:42 UTC, Garados007 commented
This PR requires PR #306 to be merged first.

2022-11-07 18:50 UTC, t-b commented
We are getting close :)

Questions:
- ReportError has a fatal parameter. The description says something about "prevent further testcase execution". But we are only adapting the message.
- There are some cases of setAbortFlag after "ReportError(... fatal = 1)".

Could we maybe fix the two issues in one go and always call `setAbortFlag()` when `fatal = 1`? Or does that not make sense?

2022-11-08 09:59 UTC, Garados007 commented
> ReportError has a fatal parameter. The description says something about "prevent further testcase execution". But we are only adapting the message.

I have seen that some messages had the prefix "Fatal:" and handled some abortion routine. I have collected these together in `ReportErrorAndAbort`. Then I have seen some places with a "Fatal:" but not immediate abortion. So I have just marked these messages as "Fatal" and didn't abort anything to do not break with current behavior. Right now the parameter `fatal=1` is nothing more than marking the message as "Fatal".

I have found 3 places with the direct use of `fatal=1` (no call to `ReportErrorAndAbort`):

- https://github.com/byte-physics/igor-unit-testing-framework/blob/5d6d63d0d28cb510bbaecc9acb22ae8a1c54bf89/procedures/unit-testing-basics.ipf#L2368-L2373
- https://github.com/byte-physics/igor-unit-testing-framework/blob/5d6d63d0d28cb510bbaecc9acb22ae8a1c54bf89/procedures/unit-testing-basics.ipf#L2379-L2384
- https://github.com/byte-physics/igor-unit-testing-framework/blob/5d6d63d0d28cb510bbaecc9acb22ae8a1c54bf89/procedures/unit-testing-basics.ipf#L3664-L3670

I can refactor these places to use `ReportErrorAndAbort` with setting the abort flag but without calling `Abort` at the end. With this `ReportError` is no longer in need for the `fatal` parameter.

> - There are some cases of setAbortFlag after "ReportError(... fatal = 1)".
> 
> Could we maybe fix the two issues in one go and always call setAbortFlag() when fatal = 1? Or does that not make sense?

With the previous suggestion of removing the the option `fatal` and calling `ReportErrorAndAbort` this will be solved in one go.

2022-11-08 10:03 UTC, Garados007 commented
What do you think about it?

2022-11-08 13:31 UTC, t-b commented
@Garados007 Sounds good!

2022-11-08 14:38 UTC, t-b commented
Would it make sense to have one function instead of `ReportError`/`ReportErrorAndAbort`? I don't know so I'm asking you.

2022-11-08 16:18 UTC, Garados007 commented
@t-b Yes, it is possible but I don't think it's the right way. If I want to combine both function I have to add more parameter to the function which increases the complexity and reduce the readability - I have to look for each call at the end of the line to know what the call is actually doing. For some messages this can be troublesome if the message is placed inline and I have to scroll for approx. 200 columns (not everyone has a 4k monitor).

Having distinct methods is better:
1. I can look at the method call to know what is the intent of the call without scrolling to the end of the line.
2. It is easier to categorize the kind of messages. I have to only search for the method name to find similar calls and I don't have to use complex regular expressions.
3. Clean methods with less complex parameter. With this I can define the default behavior for the scenarios and use parameters only as an exception to this. This also allows to write less and clean code to achieve the same result.

2022-11-08 17:07 UTC, t-b commented
@Garados007 Okay, let's keep both functions.

2022-11-10 10:53 UTC, t-b approved these changes

2022-11-10 10:53 UTC, t-b commented
@Garados007 Thanks for your patience and endurance!

2022-11-10 10:53 UTC, merged