Mb/feature/info
byte-physics/igor-unit-testing-framework pull request #319
Opened 2022-11-17 12:49 UTC by Garados007

Close #233

2022-11-18 14:24 UTC, Garados007 commented
## Update:

Current output for:
```igorpro
static Function Test7()
	variable i
	for(i = 0; i < 7; ++i)
		INFO("Loop: %d", n0 = i)
		INFO("Is smaller than 5: %d", n={ i < 5 })
		CHECK(i < 5)
	endfor
End

static Function Test8()
	INFO("empty testcase")
End
```

```
  Start of test "Unnamed"
  Entering test suite "Proc0"
  Entering test case "mymodule#Test7"
  0: is false. Assertion "CHECK(i < 5)" failed in Test7 (Proc0, line 55)
    ⓘ Loop: 5
    ⓘ Is smaller than 5: 0
  0: is false. Assertion "CHECK(i < 5)" failed in Test7 (Proc0, line 55)
    ⓘ Loop: 6
    ⓘ Is smaller than 5: 0
  Leaving test case "mymodule#Test7"
  Entering test case "mymodule#Test8"
  Test case "mymodule#Test8" doesn't contain at least one assertion
  Leaving test case "mymodule#Test8"
  Failed with 5 errors
  Leaving test suite "Proc0"
  Test finished with 5 errors
    ▶ Assertion "CHECK(i < 5)" failed in Test7 (Proc0, line 55)
    ▶ Assertion "CHECK(i < 5)" failed in Test7 (Proc0, line 55)
    ▶ Test case "mymodule#Test8" doesn't contain at least one assertion
  End of test "Unnamed"
```

2022-11-23 15:55 UTC, t-b commented
@Garados007 Can I skip this one and give that to @MichaelHuth for review? Thanks.

2022-11-23 16:19 UTC, Garados007 commented
> Can I skip this one and give that to MichaelHuth for review? Thanks.

Yes. It wasn't your turn anyway. 😉

2022-11-24 02:57 UTC, MichaelHuth requested changes
Looks like the UserPrintf routine works nicely.

I found a few things.

Also in the commit message of f551ad4e3abbc047d01748d3de530c2211ab9da8 it is "formatted"

2022-11-24 02:57 UTC, MichaelHuth commented on procedures/unit-testing-assertions.ipf
> +	else
You can pull that together to an `elseif` here.

2022-11-24 02:57 UTC, MichaelHuth commented on tests/Various.ipf
> +	INFO("This warning is intended to fail. The next testcase will search for it.")
It looks like the next testcase is not searching for it.
I think there is something like
```
	Notebook HistoryCarbonCopy, findText={"This warning is intended to fail. The next testcase will search for it.", 2}
	CHECK_EQUAL_VAR(1, V_flag)
```
missing in the CheckForWarningInHistory test case.

2022-11-24 02:57 UTC, MichaelHuth commented on tests/VTTE.ipf
> +	Ensure(!CheckUserPrintF("", "@%%d", emptyText, { 1 }, onlyErr=1))
How about an additional test for the pending RTE awareness?
e.g.
```
	variable val = str2num("a")
	Ensure(CheckUserPrintF("", "", emptyText, emptyVars,onlyErr=1))
	err = GetRTError(1)

```

2022-11-24 02:57 UTC, MichaelHuth commented on procedures/unit-testing-utils-strings.ipf
> +					sprintf str, "Cannot format number %d using format \"%s\"", numbers[numberIndex], part2
See comment above

2022-11-24 10:59 UTC, t-b commented
- Can we have an example experiment/tests which trigger all the cases where the INFO should be ouptutted and/or reset?
- Another example in the documentation?

2022-11-24 20:03 UTC, Garados007 commented
I have implemented all suggestions.

2022-11-24 21:39 UTC, MichaelHuth approved these changes
Looks good to me

2022-11-24 21:39 UTC, merged