Use UTF_PrintStatusMessage instead of printf
byte-physics/igor-unit-testing-framework pull request #348
Opened 2022-12-15 09:50 UTC by Garados007

Most calls to printf or fprintf are changed to UTF_Reporting#UTF_PrintStatusMessage. This function also ensures that the message is printed to stdout.

UTF_Reporting#UTF_PrintStatusMessage is now marked as threadsafe.

Close #329

## Dependency

- [x] PR #327

2022-12-15 10:45 UTC, Garados007 commented
I cannot make `UTF_PrintStatusMessage` threadsafe because it will fail with IMTest in Igor 8. The reason is that the line

```igorpro
	tmpStr = UTF_Utils#PrepareStringForOut(msg, maxLen = IP8_PRINTF_STR_MAX_LENGTH - 2)
```

cannot executed because it contains the full function name (module name + function name). I don't know why this limitation exists and I cannot find any reference in the documentation.

2022-12-15 10:51 UTC, Garados007 commented
I can copy the required code in the Igor 8 block to make it work. Making the required methods public or removing the threadsafe attribute does not seems to be a solution for me.

2022-12-15 14:07 UTC, t-b commented
Does `PrepareStringForOut` really have to be threadsafe? I know we default to that nowadays, but I can't see an obvious reason.

2022-12-22 09:36 UTC, Garados007 commented
1. `PrepareStringForOut` is used by `UTF_PrintStatusMessage` (unit-testing-reporting.ipf)
2. `UTF_PrintStatusMessage` is used by `Z_` (unit-testing-tracing-tracer.ipf)

`Z_` is marked as threadsafe. And #329 requested that all places that use printf to output something should use `UTF_PrintStatusMessage`. To enable this I have to mark `UTF_PrintStatusMessage` threadsafe.

2022-12-30 12:30 UTC, t-b commented
> `Z_` is marked as threadsafe. And #329 requested that all places that use printf to output something should use `UTF_PrintStatusMessage`. To enable this I have to mark `UTF_PrintStatusMessage` threadsafe.

Got it, thanks for the explanation.

2023-01-12 10:22 UTC, Garados007 commented
@t-b @MichaelHuth Ready for review.

2023-01-12 13:37 UTC, t-b commented
Review:

1e09553f (Use UTF_PrintStatusMessage instead of printf, 2022-12-15)

Mostly Good.

The change

```diff
-static Function/S PrepareStringForOut(str, [maxLen])
+threadsafe static Function/S PrepareStringForOut(str, [maxLen])
```

looks a bit odd here.

cd9a3545 (Fix UTF_PrintStatusMessage to be threadsafe in Igor 8, 2022-12-15)

- [ ] This commit needs to come before.
- [ ] Why are we now using PrepareStringForOut also for IP >= 9?
- [ ] IP8_PRINTF_STR_MAX_LENGTH was changed without justification
- [ ] Is the code duplication here really better than making PrepareForStringOutput non-static?

2023-01-12 13:39 UTC, t-b requested changes
See comment

2023-01-13 19:13 UTC, Garados007 commented
I made PrepareForStringOutput public and therefore has most of this PR changed. Please review again @t-b @MichaelHuth .

2023-01-16 14:57 UTC, t-b approved these changes

2023-01-16 14:57 UTC, merged