Add changelog for next release
byte-physics/igor-unit-testing-framework pull request #361
Opened 2022-12-28 20:40 UTC by t-b

2023-01-03 14:37 UTC, t-b commented
Documentation is deployed at https://docs-staging.byte-physics.de/igor-unit-testing-framework.

2023-01-03 15:15 UTC, Garados007 requested changes
1. The following files have no version number:
    - `procedures\unit-testing-tracing-analytics.ipf`
    - `procedures\unit-testing-tracing-auto.ipf`
    - `procedures\unit-testing-tracing-tracer.ipf`
    - `procedures\unit-testing-tracing.ipf`
2. The following files have the old copyright year:
    - `License.txt`

2023-01-03 15:17 UTC, Garados007 commented
Do we want that the test files in `tests`, `internal_dev` and `docu\examples` have a version number as well?

2023-01-03 15:27 UTC, Garados007 commented
> I don't think so. What do you think?

These test files are bound to a specific version of UTF. We can highlight this if we just add the header `#pragma version=1.09` in the `.ipf` files. Updating this in the future is pretty easy as we only need to replace one number with the other:

```bash
find . -type f -name '*.ipf' -not -path '*/\.*' -exec sed -i 's/#pragma version=1.09/#pragma version=1.10/' {} +
```

2023-01-04 11:27 UTC, t-b commented
> We can highlight this if we just add the header `#pragma version=1.09` in the `.ipf` files.

Okay. Done.

2023-01-04 15:56 UTC, t-b commented on internal_dev/TestCaseAssertionCounterCheck.ipf
> +#pragma version=1.09
Fixed.

2023-01-04 16:02 UTC, Garados007 approved these changes
LGFM

2023-01-04 16:24 UTC, merged