Rewrite of Readme.md
byte-physics/igor-unit-testing-framework pull request #382
Opened 2023-01-12 23:51 UTC by MichaelHuth

This is the rewrite of the Readme.

2023-01-13 09:41 UTC, t-b commented
Upps. I thouht I was assigned. Sorry for that. I've added some minor fixes and some more links.

2023-01-13 09:45 UTC, t-b commented
And thanks of course for the PR!

2023-01-13 09:46 UTC, Garados007 commented
Do you really want to close this PR?

2023-01-13 09:56 UTC, t-b commented
Nope, of course not. I'll make myself a coffee ;)

2023-01-13 19:47 UTC, Garados007 requested changes
It is also common to add the following sections:

- **License**. In this case we can say that most parts are BSD-3. @t-b can extend this section in his PR to reference the license file.
- **Versioning**. Are we using [Semantic Versioning](http://semver.org/)? I think so.
- **Useful Links**. We can list some good links that can help the user to use IUTF or Igor Pro.

2023-01-13 19:47 UTC, Garados007 commented on Readme.md
> +4. Have a look at the [documentation](https://docs.byte-physics.de/igor-unit-testing-framework) or the example experiments
This sounds a bit weird. Can you write something like: "Installation finished. You are ready to use IUTF in Igor Pro. Have a look..."?

2023-01-13 19:47 UTC, Garados007 commented on Readme.md
> +The Igor Pro Universal Testing Framework (IUTF) is a versatile tool to write and run tests for [Igor Pro](https://www.wavemetrics.com/products/igorpro) code.
Can you highlight the name **Igor Pro Universal Testing Framework**? You can use `**foo**` to achieve that.

2023-01-13 19:47 UTC, Garados007 commented on Readme.md
> +[![Contributors](https://img.shields.io/github/contributors-anon/byte-physics/igor-unit-testing-framework?style=plastic)](https://github.com/byte-physics/igor-unit-testing-framework/graphs/contributo
Can you add the project title has a headline? You can do this with:

```markdown
# Igor Pro Universal Testing Framework
```

After that you can list the tags.

2023-01-13 19:47 UTC, Garados007 commented on Readme.md
Can we split the following part in a new section? The current one seems a bit long. The new section could be something like "What is IUTF?" or "What can IUTF be used for?"

2023-01-13 19:47 UTC, Garados007 commented on Readme.md
I think we have to add a step before the current first one:

```markdown
1. Download the zip file attached to the newest [Release](https://github.com/byte-physics/igor-unit-testing-framework/releases). The file name is something like `UnitTestingFramework-v1.09.zip`.
```

2023-01-13 19:49 UTC, Garados007 commented
I can also create a fix if its okay.

2023-01-16 14:53 UTC, t-b commented
> It is also common to add the following sections:
> 
>     * **License**. In this case we can say that most parts are BSD-3. @t-b can extend this section in his PR to reference the license file.

Yes.

> 
>     * **Versioning**. Are we using [Semantic Versioning](http://semver.org/)? I think so.

Yes.

> 
>     * **Useful Links**. We can list some good links that can help the user to use IUTF or Igor Pro.

No, please not. This is too vague of a topic.

2023-01-16 14:55 UTC, t-b commented
@MichaelHuth Can we drop the WARN from the example? Thanks.

2023-01-18 00:17 UTC, Garados007 commented
I have added my ideas. Please take a look.

2023-01-18 00:18 UTC, Garados007 approved these changes

2023-01-18 01:08 UTC, MichaelHuth commented
Looks good to me.

Just out of curiosity, if we use semantic versioning shouldn't we be at 1.9 ?
Does the single digit leading zero for the minor version number has some intention?

2023-01-18 09:37 UTC, Garados007 commented
> if we use semantic versioning shouldn't we be at 1.9 ?

Yes there are some issues with the current versioning system that we use. The only exceptions that we have right now:

- We include leading zeros in older releases. Newer releases won't have this issue. ([according to Rule 2](https://semver.org/spec/v2.0.0.html#spec-item-2))
    I don't know why we have a leading zero at all.
- We doesn't include the patch version number. ([also Rule 2](https://semver.org/spec/v2.0.0.html#spec-item-2))

So, you are right we are not really following the rules of Semantic versioning as we break with rule 2.

I don't know. Maybe we should describe our versioning system.

2023-01-18 13:48 UTC, t-b commented
How about we just say that we want to use semantic versioning in the future and link to an issue?

I did that just now. I also revised the example a bit. And added Max and me as co authors to the commit.

2023-01-18 13:49 UTC, t-b approved these changes

2023-01-18 13:49 UTC, t-b commented
Please approve if you think this is good. Otherwise we iterate more.

2023-01-18 13:56 UTC, t-b commented
@MichaelHuth As you can't approve, it is your PR, does it look good now?

2023-01-18 14:15 UTC, merged