Use cached home path for accessing files
byte-physics/igor-unit-testing-framework pull request #394
Opened 2023-01-30 14:01 UTC by Garados007

At the start of RunTest the current home directory of the experiment file is fetched and cached in a global string. If for some reasons a test case changed to current home directory (for example storing the experiment file elsewhere) all UTF functions will still use the old home directory.

Close #287

2023-01-30 14:18 UTC, Garados007 commented
@t-b @MichaelHuth Ready for review.

2023-01-31 15:24 UTC, MichaelHuth requested changes
Yes, but how about wrapping the whole application of the homepath in a function like:
AtHome(string fileName, [variable unusedName])

2023-01-31 19:48 UTC, Garados007 commented
@MichaelHuth I have implemented your suggestion. The commit has changed a bit. Please review again.

2023-02-01 10:02 UTC, MichaelHuth approved these changes
Looks good to me.

2023-02-01 10:02 UTC, merged